name: "构建Dev镜像"
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建Dev镜像
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: wudongdefeng/jd-base
          dockerFile: docker/dev/Dockerfile
          platform: linux/amd64
          tag: unstable
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
